DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMENT VARCHAR(512) NOT NULL,
    BOOK_ID BIGINT       NOT NULL, --references BOOKS (ID) ON DELETE CASCADE
    USERNAME VARCHAR(255) NOT NULL
        );