DROP TABLE IF EXISTS COMMENTS CASCADE;
CREATE TABLE COMMENTS
(
   ID    SERIAL PRIMARY KEY,
   COMMENT VARCHAR(512) NOT NULL,
   BOOK_ID BIGINT       NOT NULL,
   USER_ID BIGINT       NOT NULL
       );