DROP TABLE IF EXISTS GENRES CASCADE;
CREATE TABLE GENRES
(
   ID   SERIAL PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL UNIQUE
       );

DROP TABLE IF EXISTS AUTHORS CASCADE;
CREATE TABLE AUTHORS
(
   ID  SERIAL PRIMARY KEY,
   NAME VARCHAR(255) NOT NULL UNIQUE
       );

DROP TABLE IF EXISTS BOOKS CASCADE;
CREATE TABLE BOOKS
(
   ID        SERIAL PRIMARY KEY,
   NAME      VARCHAR(255) NOT NULL UNIQUE,
   AUTHOR_ID BIGINT       NOT NULL references AUTHORS (ID) ON DELETE CASCADE,
   GENRE_ID  BIGINT       NOT NULL references GENRES (ID) ON DELETE CASCADE
);