INSERT INTO AUTHORS (NAME)
VALUES ('PUSHKIN');
INSERT INTO GENRES (NAME)
VALUES ('POEM');

INSERT INTO BOOKS (NAME, AUTHOR_ID, GENRE_ID)
SELECT 'EVGENII ONEGIN', A.ID, G.ID
FROM AUTHORS A, GENRES G
WHERE A.NAME = 'PUSHKIN'
AND G.NAME = 'POEM';

INSERT INTO AUTHORS (NAME)
VALUES ('MONTGOMERY');
INSERT INTO GENRES (NAME)
VALUES ('NOVEL');

INSERT INTO BOOKS (NAME, AUTHOR_ID, GENRE_ID)
SELECT 'ANNE OF GREEN GABLES', A.ID, G.ID
FROM AUTHORS A, GENRES G
WHERE A.NAME = 'MONTGOMERY'
AND G.NAME = 'NOVEL';