--DROP TABLE IF EXISTS GENRES CASCADE;
--CREATE TABLE GENRES
--(
--    ID   SERIAL PRIMARY KEY,
--    NAME VARCHAR(255) NOT NULL UNIQUE
--        );
--
--DROP TABLE IF EXISTS AUTHORS CASCADE;
--CREATE TABLE AUTHORS
--(
--    ID  SERIAL PRIMARY KEY,
--    NAME VARCHAR(255) NOT NULL UNIQUE
--        );
--
--DROP TABLE IF EXISTS BOOKS CASCADE;
--CREATE TABLE BOOKS
--(
--    ID        SERIAL PRIMARY KEY,
--    NAME      VARCHAR(255) NOT NULL UNIQUE,
--    AUTHOR_ID BIGINT       NOT NULL references AUTHORS (ID) ON DELETE CASCADE,
--    GENRE_ID  BIGINT       NOT NULL references GENRES (ID) ON DELETE CASCADE
--);
--
--DROP TABLE IF EXISTS COMMENTS CASCADE;
--CREATE TABLE COMMENTS
--(
--    ID    SERIAL PRIMARY KEY,
--    COMMENT VARCHAR(512) NOT NULL,
--    BOOK_ID BIGINT       NOT NULL references BOOKS (ID) ON DELETE CASCADE
--        );
--
--DROP TABLE IF EXISTS USERS CASCADE;
--CREATE TABLE USERS
--(
--    ID    SERIAL PRIMARY KEY,
--    USERNAME VARCHAR(255) NOT NULL UNIQUE,
--    PASSWORD VARCHAR(255) NOT NULL UNIQUE
--        );
--
--DROP TABLE IF EXISTS ROLES CASCADE;
--CREATE TABLE ROLES
--(
--    ID    SERIAL PRIMARY KEY,
--    ROLE VARCHAR(255) NOT NULL,
--    USER_ID BIGINT NOT NULL references USERS (ID) ON DELETE CASCADE
--        );

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
        );

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
        );

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL UNIQUE,
    AUTHOR_ID BIGINT       NOT NULL references AUTHORS (ID) ON DELETE CASCADE,
    GENRE_ID  BIGINT       NOT NULL references GENRES (ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMENT VARCHAR(512) NOT NULL,
    BOOK_ID BIGINT       NOT NULL references BOOKS (ID) ON DELETE CASCADE
        );

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL UNIQUE
        );

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL references USERS (ID) ON DELETE CASCADE
        );