INSERT INTO USERS (`USERNAME`, `PASSWORD`)
VALUES ('USER', 'USER');
INSERT INTO USERS (`USERNAME`, `PASSWORD`)
VALUES ('ADMIN', 'ADMIN');

INSERT INTO ROLES (`ROLE`, `USERNAME`)
VALUES ('USER',
SELECT USERNAME FROM USERS WHERE USERNAME = 'USER');

INSERT INTO ROLES (`ROLE`, `USERNAME`)
VALUES ('USER',
SELECT USERNAME FROM USERS WHERE USERNAME = 'ADMIN');

INSERT INTO ROLES (`ROLE`, `USERNAME`)
VALUES ('ADMIN',
SELECT USERNAME FROM USERS WHERE USERNAME = 'ADMIN');