INSERT INTO USERS (`USERNAME`, `PASSWORD`)
VALUES ('USER', 'USER');
INSERT INTO USERS (`USERNAME`, `PASSWORD`)
VALUES ('ADMIN', 'ADMIN');

INSERT INTO ROLES (`ROLE`, `USER_ID`)
VALUES ('USER',
SELECT ID FROM USERS WHERE USERNAME = 'USER');

INSERT INTO ROLES (`ROLE`, `USER_ID`)
VALUES ('USER',
SELECT ID FROM USERS WHERE USERNAME = 'ADMIN');

INSERT INTO ROLES (`ROLE`, `USER_ID`)
VALUES ('ADMIN',
SELECT ID FROM USERS WHERE USERNAME = 'ADMIN');