DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL UNIQUE
        );

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL references USERS (ID) ON DELETE CASCADE
        );