DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS
(
    USERNAME VARCHAR(255) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL
        );

DROP TABLE IF EXISTS ROLES CASCADE;
CREATE TABLE ROLES
(
    ROLE VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    FOREIGN KEY(USERNAME) REFERENCES USERS (USERNAME) ON DELETE CASCADE,
    PRIMARY KEY(ROLE, USERNAME),
        );