server:
  port: 7878

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false

spring:
  datasource:
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/db
    #    username: postgres
    #    password: postgres
    url: jdbc:h2:mem:testdb
  #    initialization-mode: always
  #    schema: schema.sql
  #    data: data.sql
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  #    show-sql: true

  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    health:
      show-details: always
  security:
    enabled: false